services:
  front:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/frontapp
      # 上書き防止
      - /frontapp/node_modules
      - /frontapp/.next
    ports:
      - "3030:3030"

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/backapp
    ports:
      - "8080:8080"

volumes:
  node_modules:
  .next: